image: python:2.7

variables:
  CACHE_DIR: vendor
  PIP_CACHE: $CACHE_DIR/pip
  APT_CACHE: $CACHE_DIR/apt
  NPM_CACHE: $CACHE_DIR/npm

cache:
  paths:
    - $CACHE_DIR

stages:
  - test
#  - build
#  - deploy

test:units:
  stage: test
  before_script:
    - apt-get -o dir::cache::archives="$APT_CACHE" --quiet update
    - apt-get -o dir::cache::archives="$APT_CACHE" --quiet --yes install jq psmisc
    - pip install --quiet --build $PIP_CACHE tox
  script:
    - tox -e deps
    - tox --notest
  except:
    - master

test:integration:
  stage: test
  before_script:
    - apt-get -o dir::cache::archives="$APT_CACHE" --quiet update
    - apt-get -o dir::cache::archives="$APT_CACHE" --quiet --yes --ignore-missing install $(cat tests/integration/npm-packages.txt)
    - pip install --quiet --build $PIP_CACHE -r openmtc-gevent/dependencies.txt
    - npm install --userconfig=tests/integration/.npmrc --cache=$NPM_CACHE newman
  script:
    - openmtc-gevent/run_nscl &
    - openmtc-gevent/run_gscl &
    - sleep 20
    - newman run tests/integration/gscl-all.json --environment tests/integration/environments/gscl-local.json --iteration-count 1