swagger: "2.0"
info:
  description: "REST API descrition of the ElasTest Device-emulator Service (EDS)"
  version: "1.0.0"
  title: "ElasTest Device-emulator Service REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/eds"

paths:
  

externalDocs:
  description: An elastic platform to ease end to end testing
  url: 'http://elastest.io/'
