version: '2.1'
services:
  zigbeeipe:
    container_name: zigbeeipe
    image: elastest/eds-zigbeeipe
    expose:
      - 5001
    ports:
      - 5001:5001
    networks:
      - build-eds-network

  frontend:
    container_name: frontend
    image: elastest/eds-frontend
    expose:
      - 6065
    ports:
      - 6065:6065
    networks:
      - build-eds-network

  memsipe:
    container_name: memsipe
    image: elastest/eds-memsipe
    expose:
      - 5050
    ports:
      - 5050:5050
    networks:
      - build-eds-network

networks:
  build-eds-network:
    driver: bridge
