version: '2.1'
services:
  zigbeeipe:
    container_name: zigbeeipe
    image: elastest/eds-zigbeeipe
    expose:
      - 5001
    ports:
      - 5001:5001
    networks:
      - build-image-network

networks:
  build-image-network:
    driver: bridge